// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"linkme-check/internal/biz"
	"linkme-check/internal/conf"
	"linkme-check/internal/data"
	"linkme-check/internal/server"
	"linkme-check/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	zapLogger := data.NewLogger()
	checkData := data.NewCheckData(db, zapLogger)
	checkBiz := biz.NewCheckBiz(checkData)
	checkService := service.NewCheckService(checkBiz)
	grpcServer := server.NewGRPCServer(confServer, checkService, logger)
	httpServer := server.NewHTTPServer(confServer, checkService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
