// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: api/ranking/v1/ranking.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 要获取的排名数量
}

func (x *TopNRequest) Reset() {
	*x = TopNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ranking_v1_ranking_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNRequest) ProtoMessage() {}

func (x *TopNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ranking_v1_ranking_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNRequest.ProtoReflect.Descriptor instead.
func (*TopNRequest) Descriptor() ([]byte, []int) {
	return file_api_ranking_v1_ranking_proto_rawDescGZIP(), []int{0}
}

func (x *TopNRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TopNReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TopNReply) Reset() {
	*x = TopNReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ranking_v1_ranking_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopNReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopNReply) ProtoMessage() {}

func (x *TopNReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ranking_v1_ranking_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopNReply.ProtoReflect.Descriptor instead.
func (*TopNReply) Descriptor() ([]byte, []int) {
	return file_api_ranking_v1_ranking_proto_rawDescGZIP(), []int{1}
}

func (x *TopNReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TopNReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ListTopNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListTopNRequest) Reset() {
	*x = ListTopNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ranking_v1_ranking_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopNRequest) ProtoMessage() {}

func (x *ListTopNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ranking_v1_ranking_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopNRequest.ProtoReflect.Descriptor instead.
func (*ListTopNRequest) Descriptor() ([]byte, []int) {
	return file_api_ranking_v1_ranking_proto_rawDescGZIP(), []int{2}
}

func (x *ListTopNRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTopNRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListTopNReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32               `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*GetOrListRanking `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"` // 排名列表
}

func (x *ListTopNReply) Reset() {
	*x = ListTopNReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ranking_v1_ranking_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopNReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopNReply) ProtoMessage() {}

func (x *ListTopNReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_ranking_v1_ranking_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopNReply.ProtoReflect.Descriptor instead.
func (*ListTopNReply) Descriptor() ([]byte, []int) {
	return file_api_ranking_v1_ranking_proto_rawDescGZIP(), []int{3}
}

func (x *ListTopNReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListTopNReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListTopNReply) GetData() []*GetOrListRanking {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetOrListRanking struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title        string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PostId       int64  `protobuf:"varint,4,opt,name=postId,proto3" json:"postId,omitempty"`
	UserId       int64  `protobuf:"varint,5,opt,name=userId,proto3" json:"userId,omitempty"`
	PlateId      int64  `protobuf:"varint,6,opt,name=plateId,proto3" json:"plateId,omitempty"`
	LikeCount    int64  `protobuf:"varint,7,opt,name=likeCount,proto3" json:"likeCount,omitempty"`
	CollectCount int64  `protobuf:"varint,8,opt,name=collectCount,proto3" json:"collectCount,omitempty"`
	ViewCount    int64  `protobuf:"varint,9,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
}

func (x *GetOrListRanking) Reset() {
	*x = GetOrListRanking{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ranking_v1_ranking_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrListRanking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrListRanking) ProtoMessage() {}

func (x *GetOrListRanking) ProtoReflect() protoreflect.Message {
	mi := &file_api_ranking_v1_ranking_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrListRanking.ProtoReflect.Descriptor instead.
func (*GetOrListRanking) Descriptor() ([]byte, []int) {
	return file_api_ranking_v1_ranking_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrListRanking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOrListRanking) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetOrListRanking) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetOrListRanking) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetOrListRanking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrListRanking) GetPlateId() int64 {
	if x != nil {
		return x.PlateId
	}
	return 0
}

func (x *GetOrListRanking) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetOrListRanking) GetCollectCount() int64 {
	if x != nil {
		return x.CollectCount
	}
	return 0
}

func (x *GetOrListRanking) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

var File_api_ranking_v1_ranking_proto protoreflect.FileDescriptor

var file_api_ranking_v1_ranking_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0b,
	0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x31, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x39, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x4e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22,
	0x6b, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x34, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xfc, 0x01, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x70, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x6c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x76, 0x69, 0x65, 0x77, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa7, 0x01, 0x0a, 0x07,
	0x52, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x3e, 0x0a, 0x04, 0x54, 0x6f, 0x70, 0x4e, 0x12,
	0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f,
	0x70, 0x4e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x6f, 0x70, 0x4e, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x61, 0x6e, 0x6b, 0x69,
	0x6e, 0x67, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x4e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x3a, 0x01, 0x2a, 0x22, 0x05,
	0x2f, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x6f, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x79,
	0x2f, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x65, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x61, 0x6e, 0x6b, 0x69, 0x6e,
	0x67, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ranking_v1_ranking_proto_rawDescOnce sync.Once
	file_api_ranking_v1_ranking_proto_rawDescData = file_api_ranking_v1_ranking_proto_rawDesc
)

func file_api_ranking_v1_ranking_proto_rawDescGZIP() []byte {
	file_api_ranking_v1_ranking_proto_rawDescOnce.Do(func() {
		file_api_ranking_v1_ranking_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ranking_v1_ranking_proto_rawDescData)
	})
	return file_api_ranking_v1_ranking_proto_rawDescData
}

var file_api_ranking_v1_ranking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_ranking_v1_ranking_proto_goTypes = []any{
	(*TopNRequest)(nil),      // 0: api.ranking.v1.TopNRequest
	(*TopNReply)(nil),        // 1: api.ranking.v1.TopNReply
	(*ListTopNRequest)(nil),  // 2: api.ranking.v1.ListTopNRequest
	(*ListTopNReply)(nil),    // 3: api.ranking.v1.ListTopNReply
	(*GetOrListRanking)(nil), // 4: api.ranking.v1.GetOrListRanking
}
var file_api_ranking_v1_ranking_proto_depIdxs = []int32{
	4, // 0: api.ranking.v1.ListTopNReply.data:type_name -> api.ranking.v1.GetOrListRanking
	0, // 1: api.ranking.v1.Ranking.TopN:input_type -> api.ranking.v1.TopNRequest
	2, // 2: api.ranking.v1.Ranking.ListTopN:input_type -> api.ranking.v1.ListTopNRequest
	1, // 3: api.ranking.v1.Ranking.TopN:output_type -> api.ranking.v1.TopNReply
	3, // 4: api.ranking.v1.Ranking.ListTopN:output_type -> api.ranking.v1.ListTopNReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_ranking_v1_ranking_proto_init() }
func file_api_ranking_v1_ranking_proto_init() {
	if File_api_ranking_v1_ranking_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ranking_v1_ranking_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TopNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ranking_v1_ranking_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TopNReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ranking_v1_ranking_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListTopNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ranking_v1_ranking_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListTopNReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ranking_v1_ranking_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetOrListRanking); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ranking_v1_ranking_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ranking_v1_ranking_proto_goTypes,
		DependencyIndexes: file_api_ranking_v1_ranking_proto_depIdxs,
		MessageInfos:      file_api_ranking_v1_ranking_proto_msgTypes,
	}.Build()
	File_api_ranking_v1_ranking_proto = out.File
	file_api_ranking_v1_ranking_proto_rawDesc = nil
	file_api_ranking_v1_ranking_proto_goTypes = nil
	file_api_ranking_v1_ranking_proto_depIdxs = nil
}
