// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: api/ranking/v1/ranking.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Ranking_TopN_FullMethodName     = "/api.ranking.v1.Ranking/TopN"
	Ranking_ListTopN_FullMethodName = "/api.ranking.v1.Ranking/ListTopN"
)

// RankingClient is the client API for Ranking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RankingClient interface {
	// 获取前 N 个排名
	TopN(ctx context.Context, in *TopNRequest, opts ...grpc.CallOption) (*TopNReply, error)
	// 获取分页的前 N 个排名列表
	ListTopN(ctx context.Context, in *ListTopNRequest, opts ...grpc.CallOption) (*ListTopNReply, error)
}

type rankingClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingClient(cc grpc.ClientConnInterface) RankingClient {
	return &rankingClient{cc}
}

func (c *rankingClient) TopN(ctx context.Context, in *TopNRequest, opts ...grpc.CallOption) (*TopNReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopNReply)
	err := c.cc.Invoke(ctx, Ranking_TopN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rankingClient) ListTopN(ctx context.Context, in *ListTopNRequest, opts ...grpc.CallOption) (*ListTopNReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopNReply)
	err := c.cc.Invoke(ctx, Ranking_ListTopN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServer is the server API for Ranking service.
// All implementations must embed UnimplementedRankingServer
// for forward compatibility
type RankingServer interface {
	// 获取前 N 个排名
	TopN(context.Context, *TopNRequest) (*TopNReply, error)
	// 获取分页的前 N 个排名列表
	ListTopN(context.Context, *ListTopNRequest) (*ListTopNReply, error)
	mustEmbedUnimplementedRankingServer()
}

// UnimplementedRankingServer must be embedded to have forward compatible implementations.
type UnimplementedRankingServer struct {
}

func (UnimplementedRankingServer) TopN(context.Context, *TopNRequest) (*TopNReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TopN not implemented")
}
func (UnimplementedRankingServer) ListTopN(context.Context, *ListTopNRequest) (*ListTopNReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopN not implemented")
}
func (UnimplementedRankingServer) mustEmbedUnimplementedRankingServer() {}

// UnsafeRankingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingServer will
// result in compilation errors.
type UnsafeRankingServer interface {
	mustEmbedUnimplementedRankingServer()
}

func RegisterRankingServer(s grpc.ServiceRegistrar, srv RankingServer) {
	s.RegisterService(&Ranking_ServiceDesc, srv)
}

func _Ranking_TopN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).TopN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ranking_TopN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).TopN(ctx, req.(*TopNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ranking_ListTopN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServer).ListTopN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ranking_ListTopN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServer).ListTopN(ctx, req.(*ListTopNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ranking_ServiceDesc is the grpc.ServiceDesc for Ranking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ranking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ranking.v1.Ranking",
	HandlerType: (*RankingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TopN",
			Handler:    _Ranking_TopN_Handler,
		},
		{
			MethodName: "ListTopN",
			Handler:    _Ranking_ListTopN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/ranking/v1/ranking.proto",
}
