// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"linkme-user/internal/biz"
	"linkme-user/internal/conf"
	"linkme-user/internal/data"
	"linkme-user/internal/middleware"
	"linkme-user/internal/server"
	"linkme-user/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, confService *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	cmdable := data.NewRedis(confData)
	dataData, cleanup, err := data.NewData(confData, confService, db, cmdable, logger)
	if err != nil {
		return nil, nil, err
	}
	zapLogger := data.NewLogger()
	node := data.NewSnowflake()
	userInteractive := data.NewUserData(dataData, zapLogger, node)
	userBiz := biz.NewUserBiz(userInteractive, zapLogger)
	handler := data.NewJWT(cmdable)
	userService := service.NewUserService(userBiz, handler)
	grpcServer := server.NewGRPCServer(confServer, userService)
	jwtMiddleware := middleware.NewJWTMiddleware(handler)
	httpServer := server.NewHTTPServer(confServer, userService, jwtMiddleware)
	app := newApp(confService, logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
